### ISSUE TITLE
Server Online Detection not working with first line

### ISSUE THREAD

**Issue by Moritz-Deiaco** [Moonlight-Panel/MoonlightDaemon#10]
hi, the server online detection is not working if the online confirmation is in the first console output of the Server:

for example:
you have the online detection on "Dotnet" and this word is in the first output of the server, it wont work
![image](https://github.com/Moonlight-Panel/MoonlightDaemon/assets/101179677/9cf27229-374f-4ebe-9dfd-bf9325751c0a)

**Comment by Moritz-Deiaco** [comment]
I tried it with the second line, then it worked fine

**Comment by Masu-Baumgartner** [comment]
Open a issue on the main repo
